spring.application.name=peertubeMiner
server.port=8081
loggin.level.aiss.peertubeMiner.controller=DEBUG
peertubeMiner.baseuri=https://peertube.cpy.re/api/v1

peertubeMiner.maxVideos=10
peertubeMiner.maxComments=10

videominer.uri=http://localhost:8080/videominer/channels
