spring.application.name=dailymotionMiner
server.port=8082
loggin.level.aiss.dailymotionMiner.controller=DEBUG
dailymotionMiner.baseuri=https://api.dailymotion.com

dailymotionMiner.maxVideos=10
dailymotionMiner.maxComments=10

videominer.uri=http://localhost:8080/videominer/v1
